services:
  cyber-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://arcade-master:arcade-password@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: arcade-master
      POSTGRES_PASSWORD: arcade-password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
